language: python
sudo: enabled
services:
    - mysql
python:
    - "3.6"
before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS wechat_ticket;'
# command to install dependencies
install:
    - pip install -r requirements.txt

script:
    pytest
